"""add_core_product_request_models

Revision ID: 8939844a6a1c
Revises: d6c26d38d2af
Create Date: 2025-06-17 06:55:41.397468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8939844a6a1c'
down_revision: Union[str, Sequence[str], None] = 'd6c26d38d2af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('SOFTWARE', 'HARDWARE', 'SERVICE', 'OTHER', name='producttype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('promised_delivery_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'ON_HOLD', name='requeststatus'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)

    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('quantity_proposed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'VIEWED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='proposalstatus'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)

    op.create_table('request_status_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_status_histories_id'), 'request_status_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_histories_id'), table_name='request_status_histories')
    op.drop_table('request_status_histories')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    # Manually drop Enum types if they were created with specific names for PostgreSQL
    sa.Enum(name='proposalstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='requeststatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='producttype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
